### ISSUE TITLE
Error in JSON / data not loading

### ISSUE THREAD

**Issue by rabbit83ka** [lavolp3/MMM-RainCast#4]
Since yesterday, the data isn't loading correctly, causing an error:

`[10.12.2023 10:03.50.417] [ERROR] Whoops! There was an uncaught exception...
0|MagicMir | [10.12.2023 10:03.50.421] [ERROR] SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
0|MagicMir |     at JSON.parse (<anonymous>)
0|MagicMir |     at Request._callback (/home/pi/MagicMirror/modules/MMM-RainCast/node_helper.js:49:34)
0|MagicMir |     at self.callback (/home/pi/MagicMirror/modules/MMM-RainCast/node_modules/request/request.js:185:22)
0|MagicMir |     at Request.emit (node:events:513:28)
0|MagicMir |     at Request.<anonymous> (/home/pi/MagicMirror/modules/MMM-RainCast/node_modules/request/request.js:1154:10)
0|MagicMir |     at Request.emit (node:events:513:28)
0|MagicMir |     at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/MMM-RainCast/node_modules/request/request.js:1076:12)
0|MagicMir |     at Object.onceWrapper (node:events:627:28)
0|MagicMir |     at IncomingMessage.emit (node:events:525:35)
0|MagicMir |     at endReadableNT (node:internal/streams/readable:1359:12)
0|MagicMir |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
`

**Comment by rabbit83ka** [comment]
Works again
